/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class part01_chapter13_jni_NativeDemo */

#ifndef _Included_part01_chapter13_jni_NativeDemo
#define _Included_part01_chapter13_jni_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     part01_chapter13_jni_NativeDemo
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_part01_chapter13_jni_NativeDemo_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
